name: Gem Allowlist
description: 'Requests changes on PRs that introduce gems that are not allowed'
inputs:
  gemfile:  # id of input
    description: 'the path to file we are checking'
    required: true
    default: './Gemfile'
  allowlist:  # id of input
    description: 'path to file of allowed gem names'
    required: true
    default: './allowlist.json'
  githubtoken: 
    description: 'the github token'
    required: true
    default: ${{ secrets.GH_TOKEN }}
runs:
  using: 'node16'
  main: 'dist/index.js'
