on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  read_gemfile:
    runs-on: ubuntu-latest
    name: A job to read contents of Gemfile
    with:
      githubtoken: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read Files step
        id: read-files
        uses: ./
